#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# ================================================================================================ #
# Project    : Deep Automated Essay Scoring for ELLs                                               #
# Version    : 0.1.0                                                                               #
# Python     : 3.10.4                                                                              #
# Filename   : /spacy.yml                                                                          #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john.james.ai.studio@gmail.com                                                      #
# URL        : https://github.com/john-james-ai/Deep-Automated-Essay-Scoring-for-ELLs              #
# ------------------------------------------------------------------------------------------------ #
# Created    : Tuesday September 6th 2022 06:19:50 pm                                              #
# Modified   : Tuesday September 6th 2022 09:18:05 pm                                              #
# ------------------------------------------------------------------------------------------------ #
# License    : MIT License                                                                         #
# Copyright  : (c) 2022 John James                                                                 #
# ================================================================================================ #
---
model: en_core_web_lg
components:
    - tok2vec
    - tagger
    - parser
    - ner
    - entity_linker
    - entity_ruler
    - textcat
    - textcat_multilabel
    - lemmatizer
    - trainable_lemmatizer
    - morphologizer
    - attribute_ruler
    - senter
    - sentencizer
    - transformer
...